import { ChangeDetectionStrategy, Component, inject, OnInit, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { IonButton } from '@ionic/angular/standalone';
import { Api, apiError, Page, today } from '../core/api';
import { exportCsv } from '../core/workflow';
import { FeedbackState, LoadingState, Status } from '../shared/ui';
import type { Appointment } from './receiving';
interface CalendarDay {date:string;appointments:Appointment[];count:number;}
@Component({selector:'app-agenda-calendar',standalone:true,changeDetection:ChangeDetectionStrategy.OnPush,imports:[ReactiveFormsModule,RouterLink,IonButton,FeedbackState,LoadingState,Status],template:`<section class="panel section"><h2>Calendário de recebimentos</h2><form class="filters" [formGroup]="form" (ngSubmit)="load()"><label>Data de referência<input type="date" formControlName="date" required /></label><label>Visualização<select formControlName="period"><option value="day">Dia</option><option value="week">Semana</option></select></label><label>Origem<select formControlName="origin"><option value="">Todas</option><option value="operacional_registrado">Operação registrada</option><option value="demo_sintetico">Demonstração sintética</option></select></label><ion-button type="submit" fill="outline" [disabled]="busy()||!form.controls.date.value">Consultar calendário</ion-button><ion-button type="button" fill="outline" [disabled]="busy()||!days().length" (click)="export()">Exportar agenda</ion-button><ion-button type="button" fill="outline" (click)="print()">Imprimir</ion-button></form>@if(error()){<div app-feedback tone="error">{{error()}}</div>}@if(busy()){<app-loading-state label="Carregando calendário…" />}@else{<div class="calendar-grid" [class.calendar-day]="days().length===1">@for(day of days();track day.date){<section class="calendar-column"><h3>{{label(day.date)}}</h3><p class="field-help">{{day.count}} recebimentos</p>@for(a of day.appointments;track a.id){<a class="calendar-booking" [routerLink]="['/agenda',a.id]"><strong>{{a.time.slice(0,5)}} · {{a.vehicle_plate}}</strong><span>{{a.supplier_name}}</span><small>{{a.visits.length?a.visits[0].warehouse_name:'Destino a confirmar'}}{{a.visits.length>1?' + outros destinos':''}}</small><app-status [value]="a.operation_status" /></a>}@empty{<p class="muted">Sem recebimentos.</p>}</section>}</div>}</section>`})
export class AgendaCalendar implements OnInit {
 private api=inject(Api);private fb=inject(FormBuilder);private generation=0;days=signal<CalendarDay[]>([]);busy=signal(false);error=signal('');
 form=this.fb.nonNullable.group({date:[today()],period:['day'],origin:['']});ngOnInit(){void this.load();}
 label(value:string){return new Date(value+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit'});}
 async load(){if(!this.form.controls.date.value)return;const generation=++this.generation;this.busy.set(true);this.days.set([]);this.error.set('');try{const v=this.form.getRawValue();const start=new Date(v.date+'T12:00:00');if(v.period==='week')start.setDate(start.getDate()-((start.getDay()+6)%7));const dates=Array.from({length:v.period==='week'?7:1},(_,i)=>{const date=new Date(start);date.setDate(date.getDate()+i);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;});const result=await Promise.all(dates.map(async date=>{const appointments:Appointment[]=[];let page=1,count=0;do{const response=await this.api.get<Page<Appointment>>(`appointments/?${new URLSearchParams({date,origin:v.origin,page_size:'100',page:String(page)})}`);appointments.push(...response.results);count=response.count;if(!response.next)break;page++;}while(generation===this.generation);return {date,count,appointments:appointments.sort((a,b)=>a.time.localeCompare(b.time))};}));if(generation===this.generation)this.days.set(result);}catch(e){if(generation===this.generation)this.error.set(apiError(e));}finally{if(generation===this.generation)this.busy.set(false);}}
 export(){exportCsv('agenda.csv',[['Data','Hora','Fornecedor','Veículo','Notas fiscais','Situação','Destinos'],...this.days().flatMap(d=>d.appointments.map(a=>[d.date,a.time,a.supplier_name,a.vehicle_plate,a.invoices?.map(n=>n.number).join(', ')??a.invoice_number,a.operation_status,a.visits.map(v=>v.warehouse_name).join(', ')]))]);}
 print(){window.print();}
}
