import { HttpErrorResponse } from "@angular/common/http";
import { Component, effect, inject, input, output, signal, untracked } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { IonButton } from '@ionic/angular/standalone';
import { Api, apiError } from '../core/api';
import { allowed, invoiceNumber, uploadIdentity } from '../core/workflow';
import { FeedbackState } from '../shared/ui';
import type { Appointment, InvoiceData } from './receiving';
@Component({selector:'app-appointment-edit',standalone:true,imports:[ReactiveFormsModule,IonButton,FeedbackState],template:`@if(error()){<div app-feedback tone="error">{{error()}}</div>}@if(canEdit()){<details class="panel section"><summary>Corrigir transporte ou documentos</summary><p class="muted">Trocar notas ou acondicionamento exige nova validação. Documentos com conferência registrada preservam seu vínculo.</p><form [formGroup]="form" (ngSubmit)="save()"><fieldset [disabled]="busy()"><div class="form-grid section"><label>Veículo / carreta<input formControlName="vehicle_plate" /></label><label class="check"><input type="checkbox" formControlName="articulated" />Conjunto articulado</label><label>Cavalo<input formControlName="tractor_plate" /></label><label>Transportadora<input formControlName="carrier_name" /></label><label>Motorista<input formControlName="driver_name" /></label><label>Acondicionamento<select formControlName="packaging"><option value="paletizada">Paletizada</option><option value="big_bag">Big bag</option><option value="batida">Batida exclusiva</option><option value="machine_implement">Máquina / implemento</option></select></label><label class="wide">Observações<textarea formControlName="notes"></textarea></label></div><h3 class="section">Notas vinculadas</h3>@for(invoice of documents();track invoice.id){<div class="actions"><span>NF {{invoice.number}}</span><button type="button" [disabled]="documents().length<=1" (click)="remove(invoice.id)">Remover vínculo</button></div>}<div class="form-grid section"><label>Adicionar XML ou PDF<input type="file" accept=".xml,.pdf" (change)="fileChanged($event)" /></label><label>Número da NF<input inputmode="numeric" formControlName="number" (input)="clearCache()" /></label></div><ion-button type="button" fill="outline" (click)="upload()" [disabled]="busy()||!file">Validar e adicionar documento</ion-button><div class="actions section"><ion-button type="submit" [disabled]="busy()||form.invalid||!documents().length">Salvar correção</ion-button><button type="button" (click)="reset()">Descartar alterações</button></div></fieldset></form></details>}`})
export class AppointmentEdit {
 appointment=input.required<Appointment>();changed=output<void>();updated=output<Appointment>();private preserveRevision:number|null=null;private api=inject(Api);private fb=inject(FormBuilder);busy=signal(false);error=signal('');documents=signal<InvoiceData[]>([]);file:File|null=null;private cached:{identity:string;invoice:InvoiceData}|null=null;
 form=this.fb.nonNullable.group({vehicle_plate:['',Validators.required],tractor_plate:[''],carrier_name:[''],driver_name:[''],articulated:[false],packaging:['paletizada'],notes:[''],number:['']});
 constructor(){effect(()=>{const item=this.appointment();untracked(()=>{if(this.preserveRevision===item.revision){this.preserveRevision=null;return;}this.reset();});});}
 canEdit(){return allowed(this.appointment().available_actions,'edit');}
 reset(){const a=this.appointment();this.form.reset({vehicle_plate:a.vehicle_plate,tractor_plate:a.tractor_plate??'',carrier_name:a.carrier_name??'',driver_name:a.driver_name??'',articulated:a.articulated??false,packaging:a.packaging,notes:a.notes,number:''});this.documents.set(a.invoices??[]);this.file=null;this.cached=null;}
 remove(id:string){this.documents.update(documents=>documents.filter(x=>x.id!==id));}
 clearCache(){this.cached=null;}
 fileChanged(event:Event){this.file=(event.target as HTMLInputElement).files?.[0]??null;this.clearCache();}
 async upload(){if(!this.file||this.busy())return;this.busy.set(true);this.error.set('');try{const xml=/\.xml$/i.test(this.file.name),pdf=/\.pdf$/i.test(this.file.name);if(!xml&&!pdf)throw new Error('Envie XML ou PDF.');if(this.file.size>(xml?5:10)*1024*1024)throw new Error('Arquivo excede o limite de tamanho.');const raw=this.form.controls.number.value;const number=raw.trim()?invoiceNumber(raw):'';if(pdf&&!number)throw new Error('Informe o número da NF PDF.');const identity=uploadIdentity(this.file,this.appointment().supplier,number);let invoice=this.cached?.identity===identity?this.cached.invoice:null;if(!invoice){const data=new FormData();data.append('file',this.file);if(!this.api.can('supplier'))data.append('supplier',this.appointment().supplier);if(number)data.append('number',number);invoice=await this.api.post<InvoiceData>('invoices/upload/',data);this.cached={identity,invoice};}if(!this.documents().some(x=>x.id===invoice.id))this.documents.update(documents=>[...documents,invoice]);}catch(e){this.error.set(apiError(e));}finally{this.busy.set(false);}}
 async save(){if(!this.canEdit()||this.busy()||this.form.invalid)return;this.busy.set(true);this.error.set('');try{const {number,...value}=this.form.getRawValue();void number;if(value.articulated&&!value.tractor_plate.trim())throw new Error('Informe a placa do cavalo.');const existing=this.appointment().invoices?.map(x=>x.id)??[];const selected=this.documents().map(x=>x.id);const invoice_ids=JSON.stringify(existing)!==JSON.stringify(selected)?selected:undefined;await this.api.patch(`appointments/${this.appointment().id}/`,{...value,invoice_ids,expected_revision:this.appointment().revision});this.changed.emit();}catch(e){this.error.set(apiError(e));if(e instanceof HttpErrorResponse&&e.status===409){try{const fresh=await this.api.get<Appointment>(`appointments/${this.appointment().id}/`);this.preserveRevision=fresh.revision;this.updated.emit(fresh);this.error.set(apiError(e)+' Os campos preenchidos foram preservados. A revisão atual foi carregada; confira antes de salvar novamente.');}catch(refreshError){this.error.set(apiError(e)+' '+apiError(refreshError));}}}finally{this.busy.set(false);}}
}
