import { ChangeDetectionStrategy, Component, computed, inject, OnInit, signal, viewChild } from "@angular/core";
import { FormBuilder, ReactiveFormsModule, Validators } from "@angular/forms";
import { ActivatedRoute, RouterLink } from "@angular/router";
import { IonButton } from "@ionic/angular/standalone";
import { Api, apiError, dateTime, localTimestamp, money, originLabel, today } from "../core/api";
import { Catalog, CatalogEntry } from "../core/catalog";
import { IndividualAllocation, LaborActivity } from "../core/labor-v2";
import { exportCsv } from "../core/workflow";
import { EmptyState, FeedbackState, FilterBlock, LoadingState, PageHeader } from "../shared/ui";
import { CONTRACT_LABELS } from "../core/registry";
import { WorkerForm } from "./worker-form";
import type { Appointment } from "./receiving";
interface WorkerDay {date:string;bulletin:string|null;warehouse:string|null;allocation:IndividualAllocation|null;activities:LaborActivity[];issues:{code:string;description:string}[];fraction?:string;origin:string;}
interface PayrollRecord {day:string;location:string;payroll_paid:string|null;usable:boolean;problems:unknown;source:{batch:string;sheet:string;row:string|number;column:string|number};}
interface StatementPagination {count:number;page:number;pages:number;page_size:number;next_page:number|null;previous_page:number|null;}
interface WorkerStatement {worker:CatalogEntry;period:{date_from:string;date_to:string};operational:{days:WorkerDay[];pagination:StatementPagination;totals:{total_payable:string|null;production:string|null;supplement:string|null;rounding_adjustment:string|null};coverage:Record<string,unknown>};historical_rh:{records:PayrollRecord[];pagination:StatementPagination;totals:Record<string,unknown>;quality:Record<string,unknown>}|null;}
@Component({standalone:true,changeDetection:ChangeDetectionStrategy.OnPush,imports:[ReactiveFormsModule,RouterLink,IonButton,EmptyState,FeedbackState,FilterBlock,LoadingState,PageHeader,WorkerForm],
template:`<div class="page"><a class="table-action" routerLink="/pessoas">← Todas as pessoas</a><app-page-header [title]="person()?.name ?? 'Pessoa'" [subtitle]="subtitle()">@if(api.can('warehouse')&&person()){<ion-button (click)="workerForm().open(person()!)">Editar cadastro</ion-button>}<ion-button fill="outline" [disabled]="!statement()||busy()" (click)="export()">Exportar página da apuração</ion-button><ion-button fill="outline" (click)="print()">Imprimir</ion-button></app-page-header>
@if(error()){<div app-feedback tone="error">{{error()}}</div>}@if(success()){<div app-feedback tone="success">{{success()}}</div>}
<form app-filter-block [formGroup]="filters" (ngSubmit)="load()"><label>De<input type="date" formControlName="date_from" /></label><label>Até<input type="date" formControlName="date_to" /></label><label>Origem<select formControlName="origin"><option value="operacional_registrado">Operação registrada</option><option value="demo_sintetico">Demonstração sintética</option></select></label><ion-button type="submit" [disabled]="busy() || filters.invalid">Consultar período</ion-button></form>
@if(busy()){<app-loading-state label="Consultando pessoa e período…" />}
@if(statement();as s){<section class="panel"><h2>Apuração individual</h2><p class="muted">{{origin(appliedOrigin())}} · {{s.period.date_from}} a {{s.period.date_to}}</p><div class="financial-summary"><div class="financial-total"><span>Total individual apurado</span><strong>{{money(s.operational.totals.total_payable)}}</strong><p class="field-help">Não comprova pagamento bancário ou folha de RH.</p></div><dl class="metadata"><div><dt>Produção atribuída</dt><dd>{{money(s.operational.totals.production)}}</dd></div><div><dt>Complemento</dt><dd>{{money(s.operational.totals.supplement)}}</dd></div><div><dt>Ajuste de centavos</dt><dd>{{money(s.operational.totals.rounding_adjustment)}}</dd></div></dl></div>
<div class="table-wrap section" tabindex="0" role="region" aria-label="Apuração individual por dia"><table><thead><tr><th>Dia</th><th>Armazém responsável pelo custo</th><th>Fração</th><th>Produção</th><th>Complemento</th><th>Total</th><th>Origem e pendências</th></tr></thead><tbody>@for(day of s.operational.days;track day.date+day.origin+day.bulletin){<tr><td>{{day.date}}</td><td>{{warehouse(day.warehouse)}}</td><td>{{day.fraction ?? 'Não apurada'}}</td><td>{{money(day.allocation?.display?.production)}}</td><td>{{money(day.allocation?.display?.supplement)}}</td><td>{{money(day.allocation?.display?.total_payable)}}</td><td class="wrap">@if(day.bulletin){<a [routerLink]="['/boletins',day.bulletin]">Consultar boletim</a>}@for(issue of day.issues;track $index){<p class="field-help">{{issue.description}}</p>}</td></tr>}</tbody></table></div>
<nav class="actions section" aria-label="Páginas da apuração"><ion-button type="button" fill="outline" [disabled]="busy()||s.operational.pagination.previous_page===null" (click)="changePage('days',s.operational.pagination.previous_page)">Anterior</ion-button><span>Página {{s.operational.pagination.page}} de {{s.operational.pagination.pages}} · {{s.operational.pagination.count}} registros</span><ion-button type="button" fill="outline" [disabled]="busy()||s.operational.pagination.next_page===null" (click)="changePage('days',s.operational.pagination.next_page)">Próxima</ion-button></nav><p class="field-help">Os totais e a cobertura consideram o período completo. A tabela, as atividades e a exportação mostram a página selecionada.</p>
@if(s.operational.coverage['legacy_conflict']){<p class="notice">Há dias legados com mais de um boletim para a mesma pessoa e origem. Os vínculos foram preservados e sinalizados; nenhum rateio retroativo foi inferido.</p>}
@if(!s.operational.days.length){<div app-empty-state>Nenhuma apuração operacional neste período.</div>}<details class="section"><summary>Cobertura da apuração</summary>@for(entry of entries(s.operational.coverage);track entry[0]){<p class="field-help">{{coverageLabel(entry[0])}}: {{show(entry[1])}}</p>}</details></section>
<section class="panel"><h2>Presença e atividades</h2><p class="muted">Trabalhar em vários locais não cria pagamentos adicionais. Presença e uso efetivo são registrados separadamente.</p><div class="table-wrap" tabindex="0" role="region" aria-label="Atividades da pessoa"><table><thead><tr><th>Data / local</th><th>Atividade</th><th>Presença</th><th>Utilizada</th><th>Início / fim</th><th>Ações</th></tr></thead><tbody>@for(activity of activities();track activity.id){<tr><td>{{activity.reference_date}}<small class="table-cell-secondary">{{warehouse(activity.warehouse)}}</small></td><td>{{activityLabel(activity.activity_type)}}</td><td>{{attendanceLabel(activity.attendance_state)}}</td><td>{{activity.used?'Sim':'Não confirmado'}}</td><td>{{dt(activity.started_at)}}<small class="table-cell-secondary">{{dt(activity.finished_at)}}</small></td><td>@if(api.can('warehouse')){<button type="button" (click)="editActivity(activity)">Corrigir atividade</button>}</td></tr>}</tbody></table></div></section>
<section class="panel"><h2>Histórico do RH</h2><p class="muted">Informação importada da folha original. Estes valores não são somados à apuração operacional.</p>@if(s.historical_rh;as rh){<p>Total utilizável no período completo: <strong>{{money(rh.totals['payroll_paid'])}}</strong></p><div class="table-wrap" tabindex="0" role="region" aria-label="Histórico de folha RH"><table><thead><tr><th>Data</th><th>Local</th><th>Valor na folha</th><th>Qualidade</th><th>Procedência</th></tr></thead><tbody>@for(record of rh.records;track $index){<tr><td>{{record.day}}</td><td>{{record.location}}</td><td>{{money(record.payroll_paid)}}</td><td>{{record.usable?'Utilizável':'Requer conferência'}}<small class="table-cell-secondary">{{show(record.problems)}}</small></td><td class="wrap">{{record.source.sheet}} · linha {{record.source.row}}, coluna {{record.source.column}}<small class="table-cell-secondary">Lote {{record.source.batch}}</small></td></tr>}</tbody></table></div><nav class="actions section" aria-label="Páginas do histórico de RH"><ion-button type="button" fill="outline" [disabled]="busy()||rh.pagination.previous_page===null" (click)="changePage('rh',rh.pagination.previous_page)">Anterior no RH</ion-button><span>Página {{rh.pagination.page}} de {{rh.pagination.pages}} · {{rh.pagination.count}} registros</span><ion-button type="button" fill="outline" [disabled]="busy()||rh.pagination.next_page===null" (click)="changePage('rh',rh.pagination.next_page)">Próxima no RH</ion-button></nav><details class="section"><summary>Qualidade do RH no período completo</summary>@for(entry of entries(rh.quality);track entry[0]){<p class="field-help">{{coverageLabel(entry[0])}}: {{show(entry[1])}}</p>}</details>@if(!rh.records.length){<p class="muted">Sem registros de RH neste período.</p>}}@else{<p class="notice">Consulta nominal do RH disponível apenas para Gestão e Administração.</p>}</section>}
@if(api.can('warehouse') && statement()){<form class="panel" [formGroup]="activityForm" (ngSubmit)="saveActivity()"><h2>{{activityId?'Corrigir atividade':'Registrar presença / atividade'}}</h2><fieldset [disabled]="busy()"><div class="form-grid"><label>Data<input type="date" [readOnly]="!!activityId" formControlName="reference_date" (change)="loadAppointments()" /></label><label>Local de trabalho<select formControlName="warehouse"><option value="">Selecione</option>@for(w of catalog.warehouses();track w.id){<option [value]="w.id">{{w.name}}</option>}</select></label><label>Atividade<select formControlName="activity_type"><option value="RECEIVING">Recebimento</option><option value="INTERNAL">Movimentação interna</option><option value="MACHINE">Máquina / implemento</option><option value="OTHER">Outro serviço</option></select></label><label>Presença<select formControlName="attendance_state"><option value="PLANNED">Prevista</option><option value="PRESENT">Presente</option><option value="ABSENT">Ausente</option></select></label><label>Recebimento relacionado<select formControlName="appointment"><option value="">Sem recebimento vinculado</option>@for(a of appointments();track a.id){<option [value]="a.id">{{a.vehicle_plate}} · {{a.supplier_name}} · {{a.time}}</option>}</select></label><label>Equipamento<select formControlName="equipment"><option value="">Nenhum</option>@for(e of catalog.equipment();track e.id){<option [value]="e.id">{{e.name}}</option>}</select></label><label>Início<input type="datetime-local" formControlName="started_at" /></label><label>Fim<input type="datetime-local" formControlName="finished_at" /></label><label class="check"><input type="checkbox" formControlName="used" />Uso efetivo confirmado</label><label class="wide">Observação<textarea formControlName="notes"></textarea></label>@if(activityId){<label class="wide">Motivo da correção<textarea formControlName="reason"></textarea></label>}</div><p class="field-help">Registrar atividade não calcula pagamento automaticamente. Saída parcial, hora extra ou diária especial exigem tratamento no boletim.</p><div class="actions"><ion-button type="submit" [disabled]="busy() || activityForm.invalid">Salvar atividade</ion-button>@if(activityId){<button type="button" (click)="resetActivity()">Cancelar correção</button>}</div></fieldset></form>}
<app-worker-form (saved)="workerSaved()" />
</div>`})
export class People implements OnInit {
 api=inject(Api);catalog=inject(Catalog);private fb=inject(FormBuilder);private route=inject(ActivatedRoute);
 busy=signal(false);appliedOrigin=signal('');error=signal("");success=signal("");statement=signal<WorkerStatement|null>(null);appointments=signal<Appointment[]>([]);money=money;dt=dateTime;origin=originLabel;private generation=0;
 private dayPage=1;private rhPage=1;private appliedFilters:{worker:string;date_from:string;date_to:string;origin:string}|null=null;
 filters=this.fb.nonNullable.group({worker:["",Validators.required],date_from:[today(),Validators.required],date_to:[today(),Validators.required],origin:["operacional_registrado"]});
 activityForm=this.fb.nonNullable.group({reference_date:[today(),Validators.required],warehouse:["",Validators.required],activity_type:["RECEIVING"],attendance_state:["PLANNED"],appointment:[""],equipment:[""],used:[false],started_at:[""],finished_at:[""],notes:[""],reason:[""]});
 workerForm=viewChild.required(WorkerForm);activityId="";
 person=computed(()=>this.catalog.workers().find(w=>w.id===this.workerIdParam()));workerIdParam=signal("");
 subtitle=computed(()=>{const p=this.person();if(!p)return "";return [`Matrícula ${p.registration}`,CONTRACT_LABELS[p.contract_type||"EFETIVO"],p.is_active===false?"Inativa":""].filter(Boolean).join(" · ");});private activityRevision=0;
 async ngOnInit(){this.busy.set(true);try{await this.catalog.load();const query=this.route.snapshot.queryParamMap;for(const key of ['date_from','date_to','origin'] as const){const value=query.get(key);if(value)this.filters.controls[key].setValue(value);}const id=this.route.snapshot.paramMap.get('id');if(id){this.workerIdParam.set(id);this.filters.controls.worker.setValue(id);if(!query.get('origin')&&this.person()?.origin==='demo_sintetico')this.filters.controls.origin.setValue('demo_sintetico');await this.load();}await this.loadAppointments();}catch(e){this.error.set(apiError(e));}finally{this.busy.set(false);}}
 async load(resetPages=true,dayPage=this.dayPage,rhPage=this.rhPage){if(resetPages&&this.filters.invalid)return;const generation=++this.generation;const selection=resetPages||!this.appliedFilters?this.filters.getRawValue():this.appliedFilters;const requestedDay=resetPages?1:dayPage;const requestedRh=resetPages?1:rhPage;this.busy.set(true);this.error.set("");if(resetPages)this.statement.set(null);try{const {worker,...values}=selection;const query=new URLSearchParams({...values,day_page:String(requestedDay),rh_page:String(requestedRh),page_size:'100'});const result=await this.api.get<WorkerStatement>(`workers/${worker}/statement/?${query}`);if(generation===this.generation){this.statement.set(result);this.appliedFilters={...selection};this.appliedOrigin.set(values.origin);this.dayPage=result.operational.pagination.page;this.rhPage=result.historical_rh?.pagination.page??1;if(resetPages)this.resetActivity();}}catch(e){if(generation===this.generation)this.error.set(apiError(e));}finally{if(generation===this.generation)this.busy.set(false);}}
 async changePage(section:'days'|'rh',page:number|null){if(page===null||this.busy())return;await this.load(false,section==='days'?page:this.dayPage,section==='rh'?page:this.rhPage);}
 activities(){return [...new Map((this.statement()?.operational.days.flatMap(day=>day.activities)??[]).map(activity=>[activity.id,activity])).values()];}
 warehouse(id:string|null){return this.catalog.warehouses().find(w=>w.id===id)?.name??'Não atribuído';}
 coverageLabel(value:string){return ({allocated_days:'Dias com parcelas fechadas',legacy_unallocated_days:'Boletins legados sem parcelas',legacy_conflict:'Há conflito legado de vínculo financeiro',legacy_conflict_days:'Dias e origens com conflito legado',legacy_conflict_bulletins:'Boletins envolvidos em conflito legado',partial:'Cobertura parcial',empty:'Sem registros',active_batches_only:'Somente lotes ativos',records_in_period:'Registros no período',usable_records:'Registros utilizáveis',unusable_records:'Registros não utilizáveis',undated_records_outside_period:'Registros sem data fora do período'} as Record<string,string>)[value]??value;}
 entries(value:Record<string,unknown>){return Object.entries(value);}
 show(value:unknown):string{return value==null?'Não disponível':typeof value==='boolean'?(value?'Sim':'Não'):Array.isArray(value)?value.map(x=>this.show(x)).join(' · '):typeof value==='object'?Object.entries(value).map(([k,v])=>`${k}: ${this.show(v)}`).join(' · '):String(value);}
 activityLabel(value:string){return ({RECEIVING:'Recebimento',INTERNAL:'Movimentação interna',MACHINE:'Máquina / implemento',OTHER:'Outro serviço'} as Record<string,string>)[value]??value;}
 attendanceLabel(value:string){return ({PLANNED:'Prevista',PRESENT:'Presente',ABSENT:'Ausente'} as Record<string,string>)[value]??value;}
 async loadAppointments(){if(!this.api.can('warehouse'))return;try{const result=await this.api.getAll<Appointment>(`appointments/?date=${this.activityForm.controls.reference_date.value}&page_size=100`);this.appointments.set(result);}catch(e){this.error.set(apiError(e));}}
 editActivity(a:LaborActivity){this.activityId=a.id;this.activityRevision=a.revision;const local=(date:string|null)=>date?new Date(new Date(date).getTime()-new Date(date).getTimezoneOffset()*60000).toISOString().slice(0,16):'';this.activityForm.patchValue({...a,appointment:a.appointment??'',equipment:a.equipment??'',started_at:local(a.started_at),finished_at:local(a.finished_at),reason:''});void this.loadAppointments();}
 resetActivity(){this.activityId='';this.activityRevision=0;this.activityForm.reset({reference_date:today(),warehouse:'',activity_type:'RECEIVING',attendance_state:'PLANNED',appointment:'',equipment:'',used:false,started_at:'',finished_at:'',notes:'',reason:''});}
 async saveActivity(){if(this.busy()||this.activityForm.invalid||!this.statement())return;this.busy.set(true);this.error.set('');try{const value=this.activityForm.getRawValue();if(this.activityId&&!value.reason.trim())throw new Error('Informe o motivo da correção.');const worker=this.catalog.workers().find(worker=>worker.id===this.statement()?.worker.id);const payload={...value,worker:this.statement()?.worker.id??this.filters.controls.worker.value,origin:worker?.origin==='demo_sintetico'?'demo_sintetico':'operacional_registrado',appointment:value.appointment||null,equipment:value.equipment||null,started_at:value.started_at?localTimestamp(value.started_at):null,finished_at:value.finished_at?localTimestamp(value.finished_at):null,revision:this.activityRevision||undefined,reason:this.activityId?value.reason:undefined};if(this.activityId){const {worker,reference_date,origin,...correction}=payload;void worker;void reference_date;void origin;await this.api.patch(`labor-activities/${this.activityId}/`,correction);}else await this.api.post('labor-activities/',payload);this.resetActivity();await this.load();this.success.set('Atividade salva; pagamento permanece separado da presença.');}catch(e){this.error.set(apiError(e));}finally{this.busy.set(false);}}
 workerSaved(){this.success.set('Cadastro salvo.');}
 export(){const s=this.statement();if(!s)return;exportCsv(`apuracao-${s.worker.registration}-${s.period.date_from}-pagina-${s.operational.pagination.page}.csv`,[['Matrícula','Pessoa','Data','Armazém do custo','Fração','Produção atribuída','Complemento','Total apurado','Ajuste de centavos','Boletim'],...s.operational.days.map(day=>[s.worker.registration,s.worker.name,day.date,this.warehouse(day.warehouse),day.fraction,day.allocation?.display?.production,day.allocation?.display?.supplement,day.allocation?.display?.total_payable,day.allocation?.display?.rounding_adjustment,day.bulletin])]);}
 print(){window.print();}
}
