import { Component, inject, input, output, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { IonButton } from '@ionic/angular/standalone';
import { Api, apiError } from '../core/api';
import { Catalog } from '../core/catalog';
import { quantity } from '../core/workflow';
import { decimal } from '../core/presentation';
import { FeedbackState } from '../shared/ui';
import type { Bulletin } from './bulletins';
export interface ProductionRecord {id:string;source_key:string;category:string;movement:string;quantity:string;price:string;}
@Component({selector:'app-production-records',standalone:true,imports:[ReactiveFormsModule,IonButton,FeedbackState],template:`<details class="panel section"><summary>Produção com referência de origem</summary><p class="muted">Use uma referência única do serviço, documento ou movimentação. Registros daqui são adicionados à produção: não repita a mesma quantidade na tabela de categorias.</p>@if(error()){<div app-feedback tone="error">{{error()}}</div>}<div class="table-wrap" tabindex="0" role="region" aria-label="Produção rastreável"><table><thead><tr><th>Origem</th><th>Categoria</th><th>Movimentação</th><th>Quantidade</th><th>Ação</th></tr></thead><tbody>@for(record of bulletin().production_records??[];track record.id){<tr><td>{{record.source_key}}</td><td>{{category(record.category)}}</td><td>{{movement(record.movement)}}</td><td>{{decimal(record.quantity)}}</td><td>@if(api.can('warehouse')&&bulletin().status==='DRAFT'){<button type="button" [disabled]="busy()||dirty()" (click)="edit(record)">Corrigir quantidade</button>}</td></tr>}</tbody></table></div>@if(api.can('warehouse')&&bulletin().status==='DRAFT'){<form class="section" [formGroup]="form" (ngSubmit)="save()"><fieldset [disabled]="busy()||dirty()"><div class="form-grid"><label>Referência única da origem<input formControlName="source_key" [readOnly]="!!id" /></label><label>Categoria<select formControlName="category">@for(rate of catalog.rates();track rate.code){<option [value]="rate.code">{{rate.label}}</option>}</select></label><label>Movimentação<select formControlName="movement"><option value="unloading">Descarga</option><option value="removal">Remoção</option><option value="transfer">Transferência</option></select></label><label>Quantidade<input inputmode="decimal" formControlName="quantity" /></label>@if(id){<label class="wide">Motivo da correção<textarea formControlName="reason"></textarea></label>}</div><div class="actions section"><ion-button type="submit" [disabled]="busy()||dirty()||form.invalid">{{id?'Salvar correção':'Adicionar produção'}}</ion-button>@if(id){<button type="button" (click)="clear()">Cancelar correção</button>}</div></fieldset>@if(dirty()){<p class="field-help">Salve o boletim antes de registrar uma origem.</p>}</form>}</details>`})
export class ProductionRecords {bulletin=input.required<Bulletin>();dirty=input(false);changed=output<void>();api=inject(Api);catalog=inject(Catalog);private fb=inject(FormBuilder);busy=signal(false);error=signal('');decimal=decimal;id='';form=this.fb.nonNullable.group({source_key:['',Validators.required],category:['FERTILIZANTES',Validators.required],movement:['unloading'],quantity:['',Validators.required],reason:['']});category(code:string){return this.catalog.rates().find(rate=>rate.code===code)?.label??code;}movement(code:string){return ({unloading:'Descarga',removal:'Remoção',transfer:'Transferência'} as Record<string,string>)[code]??code;}edit(record:ProductionRecord){this.id=record.id;this.form.patchValue({...record,reason:''});this.form.controls.category.disable();this.form.controls.movement.disable();}clear(){this.id='';this.form.enable();this.form.reset({source_key:'',category:'FERTILIZANTES',movement:'unloading',quantity:'',reason:''});}async save(){if(this.busy()||this.dirty()||this.form.invalid)return;this.busy.set(true);this.error.set('');try{const v=this.form.getRawValue();const amount=quantity(v.quantity);if(this.id){if(!v.reason.trim())throw new Error('Informe o motivo da correção.');await this.api.patch(`production-records/${this.id}/`,{quantity:amount,reason:v.reason,revision:this.bulletin().revision});}else{await this.api.post('production-records/',{bulletin:this.bulletin().id,source_key:v.source_key,category:v.category,movement:v.movement,quantity:amount,revision:this.bulletin().revision});}this.clear();this.changed.emit();}catch(e){this.error.set(apiError(e));}finally{this.busy.set(false);}}}
