import { Component, inject, OnInit, signal } from '@angular/core';
import { FormArray, FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { IonButton } from '@ionic/angular/standalone';
import { Api, apiError, Page } from '../core/api';
import { Catalog } from '../core/catalog';
import { quantity } from '../core/workflow';
import { decimal } from '../core/presentation';
import { FeedbackState } from '../shared/ui';
export interface PurchaseOrder {id:string;supplier:string;reference:string;confirmation_notes:string;lines:{id:string;position:number;description:string;unit:string;ordered_quantity:string;accepted_quantity:string;remaining_quantity:string}[];}
@Component({selector:'app-purchase-orders',standalone:true,imports:[ReactiveFormsModule,IonButton,FeedbackState],template:`<details class="panel section"><summary>Pedidos confirmados e saldos de entrega</summary><p class="muted">Cadastre a quantidade confirmada pelo comprador. A nota fiscal não determina o saldo do pedido.</p>@if(error()){<div app-feedback tone="error">{{error()}}</div>}@if(success()){<div app-feedback tone="success">{{success()}}</div>}<form [formGroup]="form" (ngSubmit)="save()"><fieldset [disabled]="busy()||!loaded()"><div class="form-grid"><label>Fornecedor<select formControlName="supplier" (change)="load()"><option value="">Selecione</option>@for(s of catalog.suppliers();track s.id){<option [value]="s.id">{{s.name}}</option>}</select></label><label>Referência do pedido<input formControlName="reference" /></label><label class="wide">Confirmação do comprador<textarea formControlName="confirmation_notes"></textarea></label></div><div formArrayName="lines">@for(row of lines.controls;track row;let i=$index){<div class="form-grid section" [formGroupName]="i"><label>Item {{i+1}}<input formControlName="description" /></label><label>Unidade<input formControlName="unit" /></label><label>Quantidade confirmada<input inputmode="decimal" formControlName="ordered_quantity" /></label><button type="button" [disabled]="lines.length===1" (click)="lines.removeAt(i)">Remover item</button></div>}</div><div class="actions section"><ion-button type="button" fill="outline" (click)="add()">Adicionar item</ion-button><ion-button type="submit" [disabled]="busy()||form.invalid">Confirmar pedido</ion-button></div></fieldset></form>@for(order of orders();track order.id){<section class="section"><h3>Pedido {{order.reference}}</h3><p>{{order.confirmation_notes}}</p><div class="table-wrap" tabindex="0" role="region" [attr.aria-label]="'Saldo do pedido '+order.reference"><table><thead><tr><th>Item</th><th>Unidade</th><th>Pedido confirmado</th><th>Aceito autorizado</th><th>Saldo</th></tr></thead><tbody>@for(line of order.lines;track line.id){<tr><td>{{line.description}}</td><td>{{line.unit}}</td><td>{{decimal(line.ordered_quantity)}}</td><td>{{decimal(line.accepted_quantity)}}</td><td>{{decimal(line.remaining_quantity)}}</td></tr>}</tbody></table></div></section>}</details>`})
export class PurchaseOrders implements OnInit {api=inject(Api);catalog=inject(Catalog);private fb=inject(FormBuilder);busy=signal(false);loaded=signal(false);error=signal('');success=signal('');orders=signal<PurchaseOrder[]>([]);decimal=decimal;private line=()=>this.fb.nonNullable.group({description:['',Validators.required],unit:['',Validators.required],ordered_quantity:['',Validators.required]});form=this.fb.nonNullable.group({supplier:['',Validators.required],reference:['',Validators.required],confirmation_notes:['',Validators.required],lines:new FormArray<ReturnType<PurchaseOrders['line']>>([])});get lines(){return this.form.controls.lines;}add(){this.lines.push(this.line());}async ngOnInit(){this.add();try{await this.catalog.load();this.loaded.set(true);}catch(e){this.error.set(apiError(e));}}
 async load(){const supplier=this.form.controls.supplier.value;this.orders.set([]);if(!supplier)return;try{const result=await this.api.get<Page<PurchaseOrder>>(`purchase-orders/?supplier=${supplier}&page_size=100`);if(supplier===this.form.controls.supplier.value)this.orders.set(result.results);}catch(e){this.error.set(apiError(e));}}
 async save(){if(!this.loaded()||this.busy()||this.form.invalid)return;this.busy.set(true);this.error.set('');this.success.set('');try{const value=this.form.getRawValue();await this.api.post('purchase-orders/',{...value,lines:value.lines.map(line=>({...line,ordered_quantity:quantity(line.ordered_quantity,6)}))});this.form.patchValue({reference:'',confirmation_notes:''});this.lines.clear();this.add();await this.load();this.success.set('Pedido confirmado. Vincule seus itens na conferência física de cada entrega.');}catch(e){this.error.set(apiError(e));}finally{this.busy.set(false);}}
}
