import { ChangeDetectionStrategy, Component, effect, inject, input, output, signal, untracked } from "@angular/core";
import { FormBuilder, ReactiveFormsModule, Validators } from "@angular/forms";
import { IonButton } from "@ionic/angular/standalone";
import { Api, apiError, Page } from "../core/api";
import { allowed, quantity } from "../core/workflow";
import { decimal } from "../core/presentation";
import { FeedbackState } from "../shared/ui";
import type { PurchaseOrder } from "./purchase-orders";
import type { Appointment, InvoiceData } from "./receiving";
export interface ReceiptLine {id:string;purchase_order_line?:string|null;previous_receipt_line?:string|null;invoice:string;invoice_item?:string|null;description:string;unit:string;declared_quantity:string;observed_quantity:string;accepted_quantity:string;rejected_quantity:string;discrepancy_reason:string;decision?:string;review_status?:string;}
@Component({selector:"app-receipt-check",standalone:true,changeDetection:ChangeDetectionStrategy.OnPush,imports:[ReactiveFormsModule,IonButton,FeedbackState],
template:`<section class="panel"><h2>Conferência física da carga</h2><p class="muted">Registre o observado por item. Divergências aguardam decisão de Compras antes da liberação final.</p>
@if(error()){<div app-feedback tone="error">{{error()}}</div>}@if(success()){<div app-feedback tone="success">{{success()}}</div>}
@if(appointment().receipt_lines?.length){<div class="table-wrap" tabindex="0" role="region" aria-label="Conferência por item"><table><thead><tr><th>Item</th><th>Declarado</th><th>Observado</th><th>Aceito</th><th>Recusado</th><th>Decisão</th><th>Ações</th></tr></thead><tbody>@for(line of appointment().receipt_lines;track line.id){<tr><td class="wrap">{{line.description}}<small class="table-cell-secondary">{{line.unit}} · {{line.discrepancy_reason}}</small></td><td>{{decimal(line.declared_quantity)}}</td><td>{{decimal(line.observed_quantity)}}</td><td>{{decimal(line.accepted_quantity)}}</td><td>{{decimal(line.rejected_quantity)}}</td><td>{{decisionLabel(line.decision || line.review_status)}}</td><td>@if(can('receipt-lines')){<button type="button" [disabled]="busy()" (click)="edit(line)">Corrigir linha</button>}@if(can('receipt-review')){<button type="button" [disabled]="busy()" (click)="reviewId.set(line.id)">Analisar divergência</button>}</td></tr>}</tbody></table></div>}
@if(can('receipt-lines')){<form class="section" [formGroup]="form" (ngSubmit)="save()"><fieldset [disabled]="busy()"><h3>{{editingId?'Corrigir conferência':'Adicionar item conferido'}}</h3><div class="form-grid"><label>Nota<select formControlName="invoice" (change)="invoiceChanged()"><option value="">Selecione</option>@for(invoice of invoices();track invoice.id){<option [value]="invoice.id">NF {{invoice.number}}</option>}</select></label><label>Item do XML<select formControlName="invoice_item" (change)="itemChanged()"><option value="">Linha manual de PDF</option>@for(item of selectedInvoice()?.items;track item.id){<option [value]="item.id">{{item.position}} · {{item.description}}</option>}</select></label><label>Descrição<input formControlName="description" /></label><label>Unidade<input formControlName="unit" /></label><label>Quantidade declarada<input inputmode="decimal" formControlName="declared_quantity" /></label><label>Quantidade observada<input inputmode="decimal" formControlName="observed_quantity" /></label><label>Quantidade aceita<input inputmode="decimal" formControlName="accepted_quantity" /></label><label>Quantidade recusada<input inputmode="decimal" formControlName="rejected_quantity" /></label><label>Item de pedido confirmado<select formControlName="purchase_order_line"><option value="">Sem pedido confirmado vinculado</option>@for(order of orders();track order.id){@for(line of order.lines;track line.id){<option [value]="line.id">{{order.reference}} · {{line.description}} · saldo {{decimal(line.remaining_quantity)}} {{line.unit}}</option>}}</select></label><label>Entrega anterior relacionada<select formControlName="previous_receipt_line"><option value="">Primeira entrega / sem vínculo</option>@for(previous of previousLines();track previous.line.id){<option [value]="previous.line.id">{{previous.date}} · {{previous.plate}} · {{previous.line.description}} · aceito {{decimal(previous.line.accepted_quantity)}}</option>}</select></label><label class="wide">Motivo da divergência<textarea formControlName="discrepancy_reason"></textarea></label></div><p class="field-help">Observado deve ser igual a aceito + recusado. Alterar uma conferência invalida a decisão anterior.</p><div class="actions"><ion-button type="submit" [disabled]="busy() || form.invalid">Salvar conferência</ion-button>@if(editingId){<button type="button" (click)="clear()">Cancelar correção</button>}</div></fieldset></form>}
@if(reviewId()){<form class="section" [formGroup]="reviewForm" (ngSubmit)="review()"><h3>Decisão de Compras</h3><label>Decisão<select formControlName="decision"><option value="approved">Autorizar recebimento registrado</option><option value="rejected">Rejeitar recebimento registrado</option></select></label><label>Justificativa<textarea formControlName="decision_notes"></textarea></label><div class="actions"><ion-button type="submit" [disabled]="busy() || reviewForm.invalid">Registrar decisão</ion-button><button type="button" (click)="reviewId.set('')">Cancelar</button></div></form>}
</section>`})
export class ReceiptCheck {
 appointment=input.required<Appointment>();invoices=input.required<InvoiceData[]>();changed=output<void>();api=inject(Api);private fb=inject(FormBuilder);
 orders=signal<PurchaseOrder[]>([]);previousLines=signal<{date:string;plate:string;line:ReceiptLine}[]>([]);private relatedGeneration=0;
 error=signal("");success=signal("");busy=signal(false);reviewId=signal("");editingId="";decimal=decimal;
 form=this.fb.nonNullable.group({purchase_order_line:[""],previous_receipt_line:[""],invoice:["",Validators.required],invoice_item:[""],description:[""],unit:[""],declared_quantity:[""],observed_quantity:["",Validators.required],accepted_quantity:["",Validators.required],rejected_quantity:["0",Validators.required],discrepancy_reason:[""]});
 constructor(){effect(()=>{const a=this.appointment();untracked(()=>void this.loadRelated(a));});}
 async loadRelated(a:Appointment){const generation=++this.relatedGeneration;try{const [orders,previous]=await Promise.all([this.api.get<Page<PurchaseOrder>>(`purchase-orders/?supplier=${a.supplier}&page_size=100`),this.api.get<Page<Appointment>>(`appointments/?supplier=${a.supplier}&page_size=100`)]);if(generation!==this.relatedGeneration)return;this.orders.set(orders.results);this.previousLines.set(previous.results.filter(p=>p.id!==a.id&&p.supplier===a.supplier).flatMap(p=>(p.receipt_lines??[]).map(line=>({date:p.date,plate:p.vehicle_plate,line}))));}catch(e){if(generation===this.relatedGeneration)this.error.set(apiError(e));}}
 reviewForm=this.fb.nonNullable.group({decision:["approved"],decision_notes:["",Validators.required]});
 decisionLabel(value?:string){return ({approved:'Aprovada',pending:'Aguarda Compras',rejected:'Rejeitada'} as Record<string,string>)[value??'']??'Registrada';}
 can(code:string){return allowed(this.appointment().available_actions,code);}
 selectedInvoice(){return this.invoices().find(invoice=>invoice.id===this.form.controls.invoice.value);}
 invoiceChanged(){this.form.patchValue({invoice_item:"",description:"",unit:"",declared_quantity:""});this.editingId="";}
 itemChanged(){const item=this.selectedInvoice()?.items.find(item=>item.id===this.form.controls.invoice_item.value);if(item)this.form.patchValue({description:item.description,unit:item.unit,declared_quantity:item.quantity??""});}
 edit(line:ReceiptLine){this.editingId=line.id;this.form.patchValue({...line,invoice_item:line.invoice_item??"",purchase_order_line:line.purchase_order_line??"",previous_receipt_line:line.previous_receipt_line??""});}
 clear(){this.editingId="";this.form.reset({purchase_order_line:"",previous_receipt_line:"",invoice:"",invoice_item:"",description:"",unit:"",declared_quantity:"",observed_quantity:"",accepted_quantity:"",rejected_quantity:"0",discrepancy_reason:""});}
 async save(){if(this.busy()||this.form.invalid)return;this.busy.set(true);this.error.set("");try{const value=this.form.getRawValue();const body={...value,purchase_order_line:value.purchase_order_line||null,previous_receipt_line:value.previous_receipt_line||null,invoice_item:value.invoice_item||undefined,line_id:this.editingId||undefined,declared_quantity:quantity(value.declared_quantity,6),observed_quantity:quantity(value.observed_quantity,6),accepted_quantity:quantity(value.accepted_quantity,6),rejected_quantity:quantity(value.rejected_quantity,6),expected_revision:this.appointment().revision};await this.api.post(`appointments/${this.appointment().id}/receipt-lines/`,body);this.clear();this.success.set("Conferência salva.");this.changed.emit();}catch(e){this.error.set(apiError(e));}finally{this.busy.set(false);}}
 async review(){if(this.busy()||this.reviewForm.invalid)return;this.busy.set(true);this.error.set("");try{await this.api.post(`appointments/${this.appointment().id}/receipt-review/`,{...this.reviewForm.getRawValue(),line_id:this.reviewId(),expected_revision:this.appointment().revision});this.reviewId.set("");this.success.set("Decisão registrada.");this.changed.emit();}catch(e){this.error.set(apiError(e));}finally{this.busy.set(false);}}
}
