# Generated by Django 5.2.17 on 2026-10-03 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('weight', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('group', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('document', models.CharField(blank=True, max_length=30)),
                ('origin', models.CharField(choices=[('historico_importado', 'Histórico importado'), ('operacional_registrado', 'Operação registrada'), ('demo_sintetico', 'Demonstração sintética')], default='operacional_registrado', max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('origin', models.CharField(choices=[('historico_importado', 'Histórico importado'), ('operacional_registrado', 'Operação registrada'), ('demo_sintetico', 'Demonstração sintética')], default='operacional_registrado', max_length=30)),
            ],
            options={
                'ordering': ['registration'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('mobile', models.BooleanField(default=False)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='catalog.warehouse')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depot', models.CharField(max_length=80)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='catalog.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'depot'), name='unique_product_depot')],
            },
        ),
    ]
