# Generated by Django 5.2.17 on 2026-10-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_equipment_purpose_alter_equipment_mobile_depot'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
