# Generated by Django 5.2.17 on 2026-10-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_equipment_is_active_worker_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='kind',
            field=models.CharField(blank=True, choices=[('', 'Não classificado'), ('EMPILHADEIRA_GAS', 'Empilhadeira a gás'), ('EMPILHADEIRA_ELETRICA', 'Empilhadeira elétrica / retrátil'), ('TRANSPALETEIRA_ELETRICA', 'Transpaleteira elétrica'), ('PALETEIRA_ELETRICA', 'Paleteira elétrica'), ('PALETEIRA_MANUAL', 'Paleteira manual'), ('CARRINHO', 'Carrinho de mão'), ('TRATOR', 'Trator'), ('OUTRO', 'Outro')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='worker',
            name='contract_type',
            field=models.CharField(choices=[('EFETIVO', 'Contrato anual'), ('TERCEIRIZADO', 'Terceirizado / reforço de safra')], default='EFETIVO', max_length=20),
        ),
    ]
