# Generated by Django 5.2.17 on 2026-10-03 13:18

import django.db.models.deletion
import receiving.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('packaging', models.CharField(choices=[('batida', 'Batida'), ('paletizada', 'Paletizada'), ('big_bag', 'Big bag')], max_length=20)),
                ('vehicle_plate', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('origin', models.CharField(choices=[('historico_importado', 'Histórico importado'), ('operacional_registrado', 'Operação registrada'), ('demo_sintetico', 'Demonstração sintética')], default='operacional_registrado', max_length=30)),
                ('purchase_status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=20)),
                ('order_reference', models.CharField(blank=True, max_length=100)),
                ('comparison_notes', models.TextField(blank=True)),
                ('purchase_reviewed_at', models.DateTimeField(null=True)),
                ('warehouse_status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada')], default='pending', max_length=20)),
                ('warehouse_reviewed_at', models.DateTimeField(null=True)),
                ('operation_status', models.CharField(choices=[('waiting', 'Aguardando'), ('arrived', 'Chegou'), ('in_progress', 'Em descarga'), ('completed', 'Concluída'), ('cancelled', 'Cancelada'), ('not_received', 'Não recebida')], default='waiting', max_length=20)),
                ('arrived_at', models.DateTimeField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('worker_count', models.PositiveSmallIntegerField(null=True)),
                ('resources_confirmed', models.BooleanField(default=False)),
                ('capacity_reserved', models.BooleanField(default=True)),
                ('nature_exception', models.BooleanField(default=False)),
                ('priority', models.CharField(default='scheduled', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ManyToManyField(blank=True, related_name='appointments', to='catalog.equipment')),
                ('purchase_reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_reviews', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='catalog.supplier')),
                ('warehouse_reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slot__date', 'slot__time', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('08:00', '08h'), ('10:00', '10h'), ('13:00', '13h'), ('15:00', '15h')], max_length=5)),
            ],
            options={
                'ordering': ['date', 'time'],
                'constraints': [models.UniqueConstraint(fields=('date', 'time'), name='unique_global_slot')],
            },
        ),
        migrations.CreateModel(
            name='CapacityHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units', models.PositiveSmallIntegerField()),
                ('exclusive', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_holds', to='receiving.appointment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source_appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacity_holds', to='receiving.appointment')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='receiving.globalslot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='receiving.globalslot'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=receiving.models.private_upload)),
                ('original_name', models.CharField(max_length=200)),
                ('media_type', models.CharField(max_length=50)),
                ('sha256', models.CharField(max_length=64)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('access_key', models.CharField(blank=True, max_length=44)),
                ('extracted', models.JSONField(default=dict)),
                ('extraction_status', models.CharField(default='manual', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin', models.CharField(choices=[('historico_importado', 'Histórico importado'), ('operacional_registrado', 'Operação registrada'), ('demo_sintetico', 'Demonstração sintética')], default='operacional_registrado', max_length=30)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='catalog.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='receiving.invoice'),
        ),
        migrations.CreateModel(
            name='NonReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('invoice_mismatch', 'Divergência nota/pedido'), ('unscheduled_no_capacity', 'Sem agendamento e sem vaga'), ('nature', 'Caso fortuito de natureza'), ('other', 'Outro')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('vehicle_plate', models.CharField(blank=True, max_length=30)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin', models.CharField(choices=[('historico_importado', 'Histórico importado'), ('operacional_registrado', 'Operação registrada'), ('demo_sintetico', 'Demonstração sintética')], default='operacional_registrado', max_length=30)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_receipt', to='receiving.appointment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.supplier')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceivingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=50)),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='receiving.appointment')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('supplier_code', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=22, null=True)),
                ('unit_value', models.DecimalField(decimal_places=6, max_digits=22, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receiving.invoice')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('invoice', 'position'), name='unique_invoice_item_position')],
            },
        ),
        migrations.CreateModel(
            name='WarehouseVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('worker_count', models.PositiveSmallIntegerField(null=True)),
                ('resources_confirmed', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='receiving.appointment')),
                ('equipment', models.ManyToManyField(blank=True, related_name='visits', to='catalog.equipment')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='catalog.warehouse')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('appointment', 'warehouse'), name='unique_appointment_destination'), models.UniqueConstraint(fields=('appointment', 'sequence'), name='unique_appointment_visit_sequence')],
            },
        ),
    ]
