# Generated by Django 5.2.17 on 2026-10-03 21:51

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0002_invoiceitem_unit_value_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='carrier_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='creation_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='appointment',
            name='creation_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='driver_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='appointment',
            name='gate_checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='gate_checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tractor_plate',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='workflow_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='warehousevisit',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousevisit',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='packaging',
            field=models.CharField(choices=[('batida', 'Batida'), ('paletizada', 'Paletizada'), ('big_bag', 'Big bag'), ('machine_implement', 'Máquina / implemento (exclusivo)')], max_length=20),
        ),
        migrations.CreateModel(
            name='InternalNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_role', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=300)),
                ('dedupe_key', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(null=True)),
                ('acknowledged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='receiving.appointment')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_links', to='receiving.appointment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='load_links', to='receiving.invoice')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('appointment', 'invoice'), name='one_invoice_per_load'), models.UniqueConstraint(fields=('appointment', 'position'), name='unique_load_invoice_position')],
            },
        ),
        migrations.CreateModel(
            name='ReceiptLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=400)),
                ('unit', models.CharField(max_length=30)),
                ('declared_quantity', models.DecimalField(decimal_places=6, max_digits=22)),
                ('observed_quantity', models.DecimalField(decimal_places=6, max_digits=22)),
                ('accepted_quantity', models.DecimalField(decimal_places=6, max_digits=22)),
                ('rejected_quantity', models.DecimalField(decimal_places=6, max_digits=22)),
                ('decision', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=20)),
                ('discrepancy_reason', models.TextField(blank=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='receiving.appointment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receiving.invoice')),
                ('invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='receiving.invoiceitem')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recorded_at', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('invoice_item__isnull', False)), fields=('appointment', 'invoice_item'), name='one_receipt_line_per_item_load'), models.CheckConstraint(condition=models.Q(('accepted_quantity__gte', 0), ('declared_quantity__gte', 0), ('observed_quantity__gte', 0), ('rejected_quantity__gte', 0)), name='receipt_quantities_nonnegative'), models.CheckConstraint(condition=models.Q(('observed_quantity', django.db.models.expressions.CombinedExpression(models.F('accepted_quantity'), '+', models.F('rejected_quantity')))), name='receipt_quantities_reconcile')],
            },
        ),
        migrations.CreateModel(
            name='ReceivingCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField()),
                ('action', models.CharField(max_length=80)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='receiving.appointment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('appointment', 'key'), name='unique_receiving_command')],
            },
        ),
    ]
