# Generated by Django 5.2.17 on 2026-10-03 21:32

import django.db.models.deletion
import receiving.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0002_invoiceitem_unit_value_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateArrival',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_plate', models.CharField(max_length=15)),
                ('tractor_plate', models.CharField(max_length=15)),
                ('driver_name', models.CharField(max_length=120)),
                ('invoice_number', models.CharField(max_length=44)),
                ('file', models.FileField(upload_to=receiving.models.gate_upload)),
                ('original_name', models.CharField(max_length=200)),
                ('media_type', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_arrivals', to=settings.AUTH_USER_MODEL)),
                ('seen_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_arrivals_seen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
