# Generated by Django 5.2.17 on 2026-10-03 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0003_portaria_gate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gatearrival',
            name='decided_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gatearrival',
            name='decided_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_arrivals_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatearrival',
            name='decision',
            field=models.CharField(choices=[('pending', 'Pendente'), ('authorized', 'Autorizada'), ('rejected', 'Recusada')], default='pending', max_length=20),
        ),
    ]
