# Generated by Django 5.2.17 on 2026-10-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0003_portaria_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='packaging',
            field=models.CharField(choices=[('batida', 'Batida'), ('paletizada', 'Paletizada'), ('big_bag', 'Big bag'), ('maquina_implemento', 'Máquina ou implemento')], max_length=20),
        ),
    ]
