# Generated by Django 5.2.17 on 2026-10-03 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_equipment_is_active_worker_is_active'),
        ('receiving', '0004_backfill_invoice_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='articulated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='assisted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='booking_kind',
            field=models.CharField(choices=[('legacy', 'Legado'), ('scheduled', 'Agendado'), ('spontaneous', 'Agendamento no ato')], default='legacy', max_length=20),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='previous_receipt_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complements', to='receiving.receiptline'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100)),
                ('confirmation_notes', models.TextField()),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.supplier')),
            ],
            options={
                'ordering': ['-confirmed_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=400)),
                ('unit', models.CharField(max_length=30)),
                ('ordered_quantity', models.DecimalField(decimal_places=6, max_digits=22)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='receiving.purchaseorder')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='receiptline',
            name='purchase_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='receiving.purchaseorderline'),
        ),
        migrations.CreateModel(
            name='ReceivingException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('late', 'Atraso'), ('no_show', 'Não comparecimento'), ('nature', 'Natureza'), ('invoice_mismatch', 'Divergência documental'), ('other', 'Outro')], max_length=30)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='receiving.appointment')),
            ],
            options={
                'ordering': ['recorded_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('supplier', 'reference'), name='unique_confirmed_supplier_order'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('order', 'position'), name='unique_confirmed_order_position'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_quantity__gt', 0)), name='confirmed_order_quantity_positive'),
        ),
    ]
