# Generated by Django 5.2.17 on 2026-10-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0005_release_rescheduled_source_holds'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='divergence_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='divergence_reported_at',
            field=models.DateTimeField(null=True),
        ),
    ]
