# Generated by Django 5.2.17 on 2026-10-03 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0005_appointment_articulated_appointment_assisted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='previous_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resubmissions', to='receiving.appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='resubmission_reason',
            field=models.TextField(blank=True),
        ),
    ]
