# Generated by Django 5.2.17 on 2026-10-04 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0011_merge_gate_leaves'),
        ('receiving', '0011_merge_logistics_update'),
    ]

    operations = [
    ]
