# Generated by Django 5.2.17 on 2026-10-04 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0013_merge_ocr_and_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatearrival',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_arrival', to='receiving.appointment'),
        ),
    ]
