# Generated by Django 5.2.17 on 2026-10-04 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0014_gate_arrival_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gatearrival',
            name='occurrence_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatearrival',
            name='occurrence_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_arrivals_occurrences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gatearrival',
            name='decision',
            field=models.CharField(choices=[('pending', 'Pendente'), ('occurrence', 'Ocorrência com Compras'), ('authorized', 'Autorizada'), ('rejected', 'Recusada')], default='pending', max_length=20),
        ),
    ]
