# Generated by Django 5.2.17 on 2026-10-03 21:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_equipment_is_active_worker_is_active'),
        ('receiving', '0005_appointment_articulated_appointment_assisted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='ocr/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=200)),
                ('sha256', models.CharField(max_length=64)),
                ('media_type', models.CharField(max_length=50)),
                ('suggestion', models.TextField(blank=True)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutboundDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=20)),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sending', 'Em envio'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('uncertain', 'Resultado desconhecido; conferir antes de repetir')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseReadiness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ready', models.BooleanField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='catalog.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReadinessRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot', models.JSONField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('readiness', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='integrations.warehousereadiness')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiptSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_revision', models.PositiveIntegerField()),
                ('document_manifest', models.JSONField()),
                ('manifest_sha256', models.CharField(max_length=64)),
                ('signer_name', models.CharField(max_length=160)),
                ('declaration', models.TextField()),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='receiving.appointment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('appointment', 'appointment_revision', 'actor'), name='unique_receipt_signature_revision_actor')],
            },
        ),
    ]
