# Generated by Django 5.2.17 on 2026-10-03 13:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBulletin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_date', models.DateField()),
                ('origin', models.CharField(choices=[('historico_importado', 'Histórico importado'), ('operacional_registrado', 'Operação registrada'), ('demo_sintetico', 'Demonstração sintética')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('CLOSED', 'Fechado')], default='DRAFT', max_length=10)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('floor_per_day', models.DecimalField(decimal_places=4, default=Decimal('90.1731'), max_digits=18)),
                ('calculation', models.JSONField(default=dict)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.warehouse')),
            ],
            options={
                'ordering': ['-reference_date', 'warehouse__name'],
            },
        ),
        migrations.CreateModel(
            name='BulletinRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('snapshot', models.JSONField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='labor.dailybulletin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BulletinParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fraction', models.DecimalField(decimal_places=1, max_digits=2)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.worker')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='labor.dailybulletin')),
            ],
        ),
        migrations.CreateModel(
            name='BulletinLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('SACARIA_25', 'Sacaria malas c/25'), ('SACARIA_40', 'Sacaria malas c/40'), ('SACARIA_50', 'Sacaria malas c/50'), ('FARDO_250', 'Sacaria fardo c/250'), ('FARDO_500', 'Sacaria fardo c/500'), ('PECAS', 'Peças'), ('MAQUINAS', 'Máquinas/equipamentos'), ('AGROQUIMICO', 'Agroquímico'), ('FERTILIZANTES', 'Fertilizantes'), ('SEMENTES', 'Sementes'), ('MEDICAMENTOS', 'Medicamentos'), ('ALIMENTACAO_ANIMAL', 'Alimentação animal'), ('ACESSORIOS', 'Acessórios agropecuários'), ('SERVICOS_DIVERSOS', 'Serviços diversos')], max_length=40)),
                ('unloading', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('removal', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('transfer', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='labor.dailybulletin')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('SACARIA_25', 'Sacaria malas c/25'), ('SACARIA_40', 'Sacaria malas c/40'), ('SACARIA_50', 'Sacaria malas c/50'), ('FARDO_250', 'Sacaria fardo c/250'), ('FARDO_500', 'Sacaria fardo c/500'), ('PECAS', 'Peças'), ('MAQUINAS', 'Máquinas/equipamentos'), ('AGROQUIMICO', 'Agroquímico'), ('FERTILIZANTES', 'Fertilizantes'), ('SEMENTES', 'Sementes'), ('MEDICAMENTOS', 'Medicamentos'), ('ALIMENTACAO_ANIMAL', 'Alimentação animal'), ('ACESSORIOS', 'Acessórios agropecuários'), ('SERVICOS_DIVERSOS', 'Serviços diversos')], max_length=40, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='rate_nonnegative')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailybulletin',
            constraint=models.UniqueConstraint(fields=('warehouse', 'reference_date'), name='one_bulletin_per_warehouse_date'),
        ),
        migrations.AddConstraint(
            model_name='bulletinparticipant',
            constraint=models.UniqueConstraint(fields=('bulletin', 'worker'), name='one_worker_per_bulletin'),
        ),
        migrations.AddConstraint(
            model_name='bulletinparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('fraction__in', ['0.5', '1.0'])), name='valid_bulletin_fraction'),
        ),
        migrations.AddConstraint(
            model_name='bulletinline',
            constraint=models.UniqueConstraint(fields=('bulletin', 'category'), name='one_category_per_bulletin'),
        ),
        migrations.AddConstraint(
            model_name='bulletinline',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0), ('removal__gte', 0), ('transfer__gte', 0), ('unloading__gte', 0)), name='bulletin_line_nonnegative'),
        ),
    ]
