# Generated by Django 5.2.17 on 2026-10-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinrevision',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
