# Generated by Django 5.2.17 on 2026-10-03 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_historicalstock_historicalworkerday_seedrun_and_more'),
        ('labor', '0002_bulletinrevision_recorded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybulletin',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='imports.sourcefile'),
        ),
    ]
