# Generated by Django 5.2.17 on 2026-10-03 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_equipment_is_active_worker_is_active'),
        ('labor', '0003_dailybulletin_source_file'),
        ('receiving', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybulletin',
            name='financial_version',
            field=models.CharField(default='boletim-v1', max_length=30),
        ),
        migrations.CreateModel(
            name='LaborActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('RECEIVING', 'Recebimento'), ('INTERNAL', 'Movimentação interna'), ('MACHINE', 'Máquinas / implementos'), ('OTHER', 'Outro')], max_length=20)),
                ('attendance_state', models.CharField(choices=[('PLANNED', 'Prevista'), ('PRESENT', 'Presente'), ('ABSENT', 'Ausente')], default='PLANNED', max_length=10)),
                ('used', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='receiving.appointment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.equipment')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LaborActivityRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('snapshot', models.JSONField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='labor.laboractivity')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LaborRuleOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('FRACTION', 'Fração excepcional'), ('EARLY_LEAVE', 'Saída antecipada'), ('OVERTIME', 'Horas extras'), ('SPECIAL_DAILY', 'Diária especial'), ('OTHER', 'Outra regra')], max_length=40)),
                ('description', models.TextField()),
                ('proposed_fraction', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('policy_version', models.CharField(blank=True, max_length=40)),
                ('resolution_type', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='labor.laboractivity')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_occurrences', to='labor.dailybulletin')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_occurrences', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labor_resolutions', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_date', models.DateField(db_index=True)),
                ('origin', models.CharField(choices=[('historico_importado', 'Histórico importado'), ('operacional_registrado', 'Operação registrada'), ('demo_sintetico', 'Demonstração sintética')], max_length=30)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_days', to='catalog.worker')),
            ],
        ),
        migrations.AddField(
            model_name='laboractivity',
            name='worker_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='labor.workerday'),
        ),
        migrations.CreateModel(
            name='IndividualAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bulletin_revision', models.PositiveIntegerField()),
                ('policy_version', models.CharField(default='proportional-largest-remainder-v1', max_length=40)),
                ('fraction', models.DecimalField(decimal_places=1, max_digits=2)),
                ('exact', models.JSONField()),
                ('display', models.JSONField()),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=24)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='labor.dailybulletin')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='catalog.worker')),
                ('worker_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='labor.workerday')),
            ],
        ),
        migrations.AddField(
            model_name='bulletinparticipant',
            name='worker_day',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_participation', to='labor.workerday'),
        ),
        migrations.CreateModel(
            name='BulletinDailyService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('FULL', 'Diária Completa'), ('HALF', 'Meia Diária')], max_length=8)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_services', to='labor.dailybulletin')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bulletin', 'kind'), name='unique_bulletin_daily_service'), models.CheckConstraint(condition=models.Q(('price__gte', 0), ('quantity__gte', 0)), name='daily_service_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=200)),
                ('origin', models.CharField(choices=[('historico_importado', 'Histórico importado'), ('operacional_registrado', 'Operação registrada'), ('demo_sintetico', 'Demonstração sintética')], max_length=30)),
                ('category', models.CharField(choices=[('SACARIA_25', 'Sacaria malas c/25'), ('SACARIA_40', 'Sacaria malas c/40'), ('SACARIA_50', 'Sacaria malas c/50'), ('FARDO_250', 'Sacaria fardo c/250'), ('FARDO_500', 'Sacaria fardo c/500'), ('PECAS', 'Peças'), ('MAQUINAS', 'Máquinas/equipamentos'), ('AGROQUIMICO', 'Agroquímico'), ('FERTILIZANTES', 'Fertilizantes'), ('SEMENTES', 'Sementes'), ('MEDICAMENTOS', 'Medicamentos'), ('ALIMENTACAO_ANIMAL', 'Alimentação animal'), ('ACESSORIOS', 'Acessórios agropecuários'), ('SERVICOS_DIVERSOS', 'Serviços diversos')], max_length=40)),
                ('movement', models.CharField(choices=[('unloading', 'Descarga'), ('removal', 'Remoção'), ('transfer', 'Transferência')], max_length=15)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_records', to='labor.dailybulletin')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_key', 'origin'), name='unique_production_source_origin'), models.CheckConstraint(condition=models.Q(('price__gte', 0), ('quantity__gte', 0)), name='production_record_nonnegative')],
            },
        ),
        migrations.AddConstraint(
            model_name='workerday',
            constraint=models.UniqueConstraint(fields=('worker', 'reference_date', 'origin'), name='unique_worker_day_origin'),
        ),
        migrations.AddConstraint(
            model_name='individualallocation',
            constraint=models.UniqueConstraint(fields=('bulletin', 'bulletin_revision', 'worker'), name='unique_individual_allocation_revision'),
        ),
    ]
