# Generated by Django 5.2.17 on 2026-10-04 02:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_equipment_kind_quantity_worker_contract'),
        ('imports', '0003_historicalstock_historicalworkerday_seedrun_and_more'),
        ('labor', '0004_dailybulletin_financial_version_laboractivity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('SACARIA_25', 'Sacaria malas c/25'), ('SACARIA_40', 'Sacaria malas c/40'), ('SACARIA_50', 'Sacaria malas c/50'), ('FARDO_250', 'Sacaria fardo c/250'), ('FARDO_500', 'Sacaria fardo c/500'), ('PECAS', 'Peças'), ('MAQUINAS', 'Máquinas/equipamentos'), ('AGROQUIMICO', 'Agroquímico'), ('FERTILIZANTES', 'Fertilizantes'), ('SEMENTES', 'Sementes'), ('MEDICAMENTOS', 'Medicamentos'), ('ALIMENTACAO_ANIMAL', 'Alimentação animal'), ('ACESSORIOS', 'Acessórios agropecuários'), ('SERVICOS_DIVERSOS', 'Serviços diversos')], max_length=40)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='TariffTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateField(unique=True)),
                ('floor_per_day', models.DecimalField(decimal_places=4, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='WorkerAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_date', models.DateField(db_index=True)),
                ('origin', models.CharField(choices=[('historico_importado', 'Histórico importado'), ('operacional_registrado', 'Operação registrada'), ('demo_sintetico', 'Demonstração sintética')], max_length=30)),
                ('kind', models.CharField(choices=[('OVERTIME', 'Hora extra confirmada'), ('EARLY_LEAVE', 'Saída antecipada'), ('SPECIAL_DAILY', 'Diária especial'), ('DISCOUNT', 'Desconto'), ('OTHER', 'Outro')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['reference_date', 'created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='bulletinline',
            name='one_category_per_bulletin',
        ),
        migrations.AddField(
            model_name='bulletinline',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.warehouse'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.warehouse'),
        ),
        migrations.AlterField(
            model_name='dailybulletin',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='bulletinline',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', True)), fields=('bulletin', 'category'), name='one_category_per_bulletin'),
        ),
        migrations.AddConstraint(
            model_name='bulletinline',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', False)), fields=('bulletin', 'warehouse', 'category'), name='one_category_per_bulletin_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='dailybulletin',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', True)), fields=('reference_date', 'origin'), name='one_daily_bulletin_per_date_origin'),
        ),
        migrations.AddField(
            model_name='tarifftable',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tariffrate',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='labor.tarifftable'),
        ),
        migrations.AddField(
            model_name='workeradjustment',
            name='bulletin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='labor.dailybulletin'),
        ),
        migrations.AddField(
            model_name='workeradjustment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_labor_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workeradjustment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workeradjustment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='catalog.worker'),
        ),
        migrations.AddConstraint(
            model_name='tarifftable',
            constraint=models.CheckConstraint(condition=models.Q(('floor_per_day__gte', 0)), name='tariff_floor_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='tariffrate',
            constraint=models.UniqueConstraint(fields=('table', 'code'), name='one_rate_per_tariff_table'),
        ),
        migrations.AddConstraint(
            model_name='tariffrate',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='tariff_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='workeradjustment',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='adjustment_nonzero'),
        ),
    ]
