# Generated by Django 5.2.17 on 2026-10-04 02:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_equipment_kind_quantity_worker_contract'),
        ('labor', '0005_daily_bulletin_tariffs_adjustments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('origin', models.CharField(choices=[('historico_importado', 'Histórico importado'), ('operacional_registrado', 'Operação registrada'), ('demo_sintetico', 'Demonstração sintética')], default='operacional_registrado', max_length=30)),
                ('period', models.CharField(choices=[('FULL', 'Integral'), ('MORNING', 'Manhã'), ('AFTERNOON', 'Tarde')], default='FULL', max_length=10)),
                ('activity', models.CharField(choices=[('OPERATION', 'Descarga e carregamento'), ('ORGANIZATION', 'Organização interna')], default='OPERATION', max_length=15)),
                ('attendance', models.CharField(choices=[('PLANNED', 'Escalado'), ('PRESENT', 'Presente'), ('ABSENT', 'Falta')], default='PLANNED', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.warehouse')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_shifts', to='catalog.worker')),
            ],
            options={
                'ordering': ['date', 'worker__registration'],
                'constraints': [models.UniqueConstraint(fields=('worker', 'date', 'origin'), name='one_roster_shift_per_worker_day')],
            },
        ),
    ]
