# Generated by Django 5.2.17 on 2026-10-03 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(db_index=True, max_length=40)),
                ('file_hash', models.CharField(max_length=64)),
                ('importer_version', models.CharField(max_length=20)),
                ('source_name', models.CharField(max_length=255)),
                ('origin', models.CharField(default='historico_importado', editable=False, max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(default=dict)),
                ('issues', models.JSONField(default=dict)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'file_hash', 'importer_version'), name='unique_import_version'), models.UniqueConstraint(condition=models.Q(('active', True)), fields=('kind',), name='one_active_import_kind')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_sheet', models.CharField(max_length=100)),
                ('source_row', models.PositiveIntegerField()),
                ('origin', models.CharField(default='historico_importado', editable=False, max_length=30)),
                ('purchase_order', models.CharField(blank=True, db_index=True, max_length=80)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('supplier_code', models.CharField(blank=True, max_length=80)),
                ('product_code', models.CharField(blank=True, max_length=80)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('reported_order_weight', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('depot', models.CharField(blank=True, db_index=True, max_length=80)),
                ('receipt_number', models.CharField(blank=True, db_index=True, max_length=80)),
                ('received_on', models.DateField(blank=True, db_index=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=80)),
                ('invoice_key', models.CharField(blank=True, max_length=100)),
                ('original', models.JSONField(default=dict)),
                ('problems', models.JSONField(default=list)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.supplier')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='imports.importbatch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'source_row'), name='unique_history_source_row')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLaborDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_row', models.PositiveIntegerField()),
                ('origin', models.CharField(default='historico_importado', editable=False, max_length=30)),
                ('day', models.DateField(db_index=True)),
                ('weekday', models.CharField(blank=True, max_length=20)),
                ('worker_count', models.PositiveIntegerField()),
                ('coffee_worker_count', models.PositiveIntegerField()),
                ('payroll_paid', models.DecimalField(decimal_places=6, max_digits=20)),
                ('original', models.JSONField(default=dict)),
                ('problems', models.JSONField(default=list)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_days', to='imports.importbatch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'source_row'), name='unique_labor_source_row')],
            },
        ),
        migrations.CreateModel(
            name='SourceRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_sheet', models.CharField(blank=True, max_length=100)),
                ('source_row', models.PositiveIntegerField()),
                ('natural_key', models.CharField(blank=True, max_length=200)),
                ('original', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_rows', to='imports.importbatch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'source_sheet', 'source_row'), name='unique_source_row')],
            },
        ),
    ]
