# Generated by Django 5.2.17 on 2026-10-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcerow',
            name='problems',
            field=models.JSONField(default=list),
        ),
    ]
