# Generated by Django 5.2.17 on 2026-10-03 19:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_equipment_purpose_alter_equipment_mobile_depot'),
        ('imports', '0002_source_row_problems'),
        ('receiving', '0002_invoiceitem_unit_value_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_sheet', models.CharField(max_length=100)),
                ('source_row', models.PositiveIntegerField()),
                ('product_code', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('snapshot_on', models.DateField(blank=True, null=True)),
                ('origin', models.CharField(default='historico_importado', editable=False, max_length=30)),
                ('original', models.JSONField(default=dict)),
                ('problems', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalWorkerDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_sheet', models.CharField(max_length=100)),
                ('source_row', models.PositiveIntegerField()),
                ('source_column', models.PositiveIntegerField()),
                ('source_identifier', models.CharField(max_length=40)),
                ('declared_date', models.CharField(blank=True, max_length=100)),
                ('day', models.DateField(blank=True, db_index=True, null=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('payroll_paid', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('usable', models.BooleanField(default=False)),
                ('origin', models.CharField(default='historico_importado', editable=False, max_length=30)),
                ('original', models.JSONField(default=dict)),
                ('problems', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='SeedRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=40, unique=True)),
                ('manifest_hash', models.CharField(max_length=64)),
                ('manifest', models.JSONField()),
                ('summary', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relative_path', models.CharField(max_length=500)),
                ('file', models.FileField(max_length=500, upload_to='')),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveBigIntegerField()),
                ('kind', models.CharField(max_length=40)),
                ('problems', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='importbatch',
            name='unique_import_version',
        ),
        migrations.RemoveConstraint(
            model_name='importbatch',
            name='one_active_import_kind',
        ),
        migrations.AddField(
            model_name='importbatch',
            name='source_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_rows', to='imports.importbatch'),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.depot'),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
        migrations.AddField(
            model_name='historicalworkerday',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_days', to='imports.importbatch'),
        ),
        migrations.AddField(
            model_name='historicalworkerday',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.worker'),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_files', to='receiving.invoice'),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='seed_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='imports.seedrun'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='imports.sourcefile'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('kind', 'source_key', 'file_hash', 'importer_version'), name='unique_import_version'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('kind', 'source_key'), name='one_active_import_kind'),
        ),
        migrations.AddConstraint(
            model_name='historicalstock',
            constraint=models.UniqueConstraint(fields=('batch', 'source_sheet', 'source_row'), name='unique_stock_source_row'),
        ),
        migrations.AddConstraint(
            model_name='historicalworkerday',
            constraint=models.UniqueConstraint(fields=('batch', 'source_sheet', 'source_row', 'source_column'), name='unique_worker_day_cell'),
        ),
        migrations.AddConstraint(
            model_name='sourcefile',
            constraint=models.UniqueConstraint(fields=('seed_run', 'relative_path'), name='unique_seed_source_file'),
        ),
    ]
