# Generated by Django 5.2.17 on 2026-10-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('supplier', 'Fornecedor'), ('purchasing', 'Compras'), ('warehouse', 'Armazém'), ('gatehouse', 'Portaria'), ('management', 'Gestão'), ('admin', 'Administrador')], max_length=20),
        ),
    ]
